from telegram import  KeyboardButton,ReplyKeyboardMarkup

TOKEN = '1821123387:AAGgFhuE0PW5yqB8BxYcVow7VQyFOFX2D2I'

order_button = [KeyboardButton(text = 'Сделать заказ')]
top_button = [KeyboardButton(text='Позвать Таймгарда🏃')]
mid_button = [KeyboardButton(text='Продуть Кальян💨')]
bot_button = [KeyboardButton(text='Попросить счет💵')]
bar_button = [KeyboardButton(text='Кухня')]
shisha_button = [KeyboardButton(text='Кальян')]
kitchen_button = [KeyboardButton(text='Бар')]
easy = [KeyboardButton(text='Легкий')]
medium = [KeyboardButton(text='Средний')]
rare = [KeyboardButton(text='Крепкий')]
berry = [KeyboardButton(text ='Ягодный')]
fruit = [KeyboardButton(text = 'Фруктовый')]
citrus = [KeyboardButton(text = 'Цитрусовый')]
desert = [KeyboardButton(text = 'Десертный')]
kolaud = [KeyboardButton(text='Калауд')]
folga = [KeyboardButton(text= 'Фольга')]
ice = [KeyboardButton(text = 'С холодком')]
no_ice = [KeyboardButton(text = 'Без Холодка')]
yes =[KeyboardButton(text = 'Да')]
no = [KeyboardButton(text = 'Выбрать что-нибудь еще')]

five_star = [KeyboardButton(text='⭐⭐⭐⭐⭐')]
four_star = [KeyboardButton(text="⭐⭐⭐⭐")]
three_star = [KeyboardButton(text="⭐⭐⭐")]
two_star = [KeyboardButton(text="⭐⭐")]
one_star = [KeyboardButton(text="⭐")]
restart = [KeyboardButton(text = '/start')]
